### ISSUE TITLE
Child hidden states not summed correctly to parent offset locations?

### ISSUE THREAD

**Issue by cjb06776** [unbounce/pytorch-tree-lstm#2]
Hello,

Thanks for the interesting blog post.

I think there may be an error with line:  https://github.com/unbounce/pytorch-tree-lstm/blob/master/treelstm/tree_lstm.py#L98 

```
            # Add child hidden states to parent offset locations
            h_sum[parent_indexes, :] += h[child_indexes, :]
```

For a concrete example, in the third iteration of the toy data example, with parent_indexes at ```[0, 0]``` and child_indexes are ```[1, 2]``` 

h_sum is:```tensor([[ 0.0000], [ 0.0000], [-0.0224], [ 0.0000]], grad_fn=<CopySlices>)```

h is: ```tensor([[ 0.0000], [ 0.1170], [-0.0494], [-0.0224]], grad_fn=<CopySlices>)```

However, after that L98 runs, I observe that h_sum[0] = -0.0494.  

```
tensor([[-0.0494], [ 0.0000], [-0.0224], [ 0.0000]], grad_fn=<CopySlices>)
```

Unless I'm reading it wrong, this doesn't seem expected?   I would expect new h_sum[0] to be h_sum[0] + h[1] + h[2] = 0 + 0.1170 + -0.0494 = 0.06760?

**Comment by freedryk** [comment]
That indeed doesn't seem expected.  Investigating.  This was just running on the default example?  What version of pytorch and python are you running?

**Comment by freedryk** [comment]
I pushed a fix to master that should resolve this.  Can you verify?

**Comment by freedryk** [comment]
Many thanks.
