### ISSUE TITLE
Parent cell states not summed correctly?

### ISSUE THREAD

**Issue by cjb06776** [unbounce/pytorch-tree-lstm#3]
Hello,

I noticed what I think is another instance of something similar as was occuring in https://github.com/unbounce/pytorch-tree-lstm/issues/2.

https://github.com/unbounce/pytorch-tree-lstm/blob/952895a6920dc304d20d4cf8d96fdebb26b7276d/treelstm/tree_lstm.py#L122

Same scenario, in the third iteration of the toy data example, with parent_indexes at [0, 0] and child_indexes are [1, 2].

fc is:  ```tensor([[0.0317], [0.1887]], grad_fn=<MulBackward0>)```

c is ```tensor([[0.3349], [0.0474], [0.2817], [0.3188]], grad_fn=<CopySlices>)```

Updating from L122 only ends up adding the 2nd fc value, resulting in c[0] value of 0.5236.  Where the expected value should be c[0] + fc[0] + fc[1] = 0.3349 + 0.0317 + 0.1887 = 0.5553

``` tensor([[0.5236], [0.0474], [0.2817], [0.3188]], grad_fn=<CopySlices>)```

**Comment by freedryk** [comment]
You are correct.  I pushed a fix, and I checked for this bug occurring again--I don't see it elsewhere.  Sorry, I should have checked for multiple occurrences of this pattern myself.  Thanks so much for your diligence!
