### ISSUE TITLE
Why should the length of hidden state must be the same with the length of label?

### ISSUE THREAD

**Issue by zrg1993** [unbounce/pytorch-tree-lstm#6]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-46-d159da2f22b8> in <module>()
     27     labels = data['labels']
     28 
---> 29     loss = loss_function(h, labels)
     30     loss.backward()
     31     optimizer.step()

~/pytorch/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/pytorch/torch/nn/modules/loss.py in forward(self, input, target)
    574                                                   self.weight,
    575                                                   pos_weight=self.pos_weight,
--> 576                                                   reduction=self.reduction)
    577 
    578 

~/pytorch/torch/nn/functional.py in binary_cross_entropy_with_logits(input, target, weight, size_average, reduce, reduction, pos_weight)
   1774 
   1775     if not (target.size() == input.size()):
-> 1776         raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
   1777 
   1778     return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction)

ValueError: Target size (torch.Size([4, 2])) must be the same as input size (torch.Size([4, 1]))

**Comment by freedryk** [comment]
It doesn't have to be, but the example model setup I have assumes that is the case.  To output an arbitrary number of label predictions from the TreeLSTM hidden state you should put more nn layers after the TreeLSTM layer that convert the hidden layer neuron activations into the number of label predictions you require.
